version: '3.8'

services:

  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - "9090:9090"
      - "9100:9100"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:8.2.2
    ports:
      - "3000:3000"
      - "4000:4000"
    networks:
      - monitoring

  sonarqube:
    image: sonarqube:8.9.3-community
    ports:
      - "9000:9000"
      - "10000:10000"
    networks:
      - monitoring

  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - monitoring

  nexus:
    image: sonatype/nexus3:3.37.0
    ports:
      - "8081:8081"
      - "8082:8082"
    networks:
      - monitoring

  vault:
    image: hashicorp/vault:1.7.3
    ports:
      - "8200:8200"
    networks:
      - monitoring

  keycloak:
    image: jboss/keycloak:15.0.2
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "8083:8083"
    networks:
      - monitoring

networks:
  monitoring:
volumes:
  jenkins_home:
